.\"
.\" Copyright (c) 2011 2012 2013 ... 2022 2023
.\"     John McCue <jmccue@jmcunx.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.TH IS_NUMERIC 1 "2011-05-15" "JMC" "User Commands"
.SH NAME
is_number - simple program to check for a numeric value.
.SH SYNOPSIS
is_number [value...]
.SH DESCRIPTION
Simple program to check to see if
a value(s) is numeric (ie: an integer).
Probably only useful in shell scripts.
.P
The argument is a list of one or more values
to validate.
.SH DIAGNOSTICS
The 'value' must be all numeric.
If it contains a decimal point or thousand separator,
the value is NOT considered numeric.
.PP
If no arguments are specified,
zero is returned.
.SH ERROR-CODES
.nf
0 the value(s) are numeric
1 the value(s) are not numeric
.fi
